version: '3.9'
services:
  classification_service:
    build:
      context: ./classification
    ports:
      - "5000:5000"
  clustering_service:
    build:
      context: ./clustering
    restart: always
    ports:
      - "5001:5001"
  data_preparation_service:
    build:
      context: ./dataPreparation
    ports:
      - "5002:5002"        
 