openapi: "3.0.0"
info:
  version: 1.0.0
  title: QHana Classification API
  license:
    name: MIT
servers:
  - url: http://localhost:5050/v1.0
paths:
  /variational-svm-classification/initialization/{job_id}:
    post:
      summary: Initialize Classifier
      operationId: resources.classifier.Classifier.initialize
      tags:
        - classifiers
      parameters:
        - name: job_id
          in: path
          description: Job identifier
          required: true
          schema:
            type: string
        - name: data_url
          in: query
          description: data_url
          required: true
          schema:
            type: string
        - name:  optimizer_parameters_url
          in: query
          description: optimizer_parameters_url
          required: true
          schema:
            type: string
        - name: entanglement
          in: query
          description: entanglement
          required: true
          schema:
            type: string
            default: full
        - name: feature_map_reps
          in: query
          description: feature_map_reps
          required: true
          schema:
            type: integer
            default: 1
        - name: variational_form_reps
          in: query
          description: variational_form_reps
          required: true
          schema:
            type: integer
            default: 3
      responses:
        '200':
          description: Initialization Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitResponse"
        '404':
          description: Classifier not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /variational-svm-classification/parameterization-generation/{job_id}:
    post:
      summary: Generate circuit parameterizations
      operationId: resources.classifier.Classifier.generates_circuit_parameterizations
      tags:
        - classifiers
      parameters:
        - name: job_id
          in: path
          description: Job identifier
          required: true
          schema:
            type: string
        - name: data_url
          in: query
          description: data_url
          required: true
          schema:
            type: string
        - name:  circuit_template_url
          in: query
          description: circuit_template_url
          required: true
          schema:
            type: string
        - name: thetas_url
          in: query
          description: thetas_url
          required: true
          schema:
            type: string
        - name: thetas_plus_url
          in: query
          description: thetas_plus_url
          required: true
          schema:
            type: string
        - name: thetas_minus_url
          in: query
          description: thetas_minus_url
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Generate circuit Parameterizations Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenResponse"
        '404':
          description: Classifier not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /variational-svm-classification/circuit-execution/{job_id}:
    post:
      summary: Execute Circuits
      operationId: resources.classifier.Classifier.execute_circuits
      tags:
        - classifiers
      parameters:
        - name: job_id
          in: path
          description: Job identifier
          required: true
          schema:
            type: string
        - name: circuit_template_url
          in: query
          description: circuit_template_url
          required: true
          schema:
            type: string
        - name:  parameterizations_url
          in: query
          description: parameterizations_url
          required: true
          schema:
            type: string
        - name: backend_name
          in: query
          description: backend_name
          required: true
          schema:
            type: string
        - name: token
          in: query
          description: token
          required: true
          schema:
            type: string
        - name: shots
          in: query
          description: shots
          required: true
          schema:
            type: integer
            default: 1024
      responses:
        '200':
          description: Initialization Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExeResponse"
        '404':
          description: Classifier not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /variational-svm-classification/optimization/{job_id}:
    post:
      summary: Optimize parameters
      operationId: resources.classifier.Classifier.optimize
      tags:
        - classifiers
      parameters:
        - name: job_id
          in: path
          description: Job identifier
          required: true
          schema:
            type: string
        - name: results_url
          in: query
          description: results_url
          required: true
          schema:
            type: string
        - name:  labels_url
          in: query
          description: labels_url
          required: true
          schema:
            type: string
        - name: thetas_in_url
          in: query
          description: thetas_in_url
          required: true
          schema:
            type: string
        - name: delta_in_url
          in: query
          description: delta_in_url
          required: true
          schema:
            type: string
        - name: optimizer_parameters_url
          in: query
          description: optimizer_parameters_url
          required: true
          schema:
            type: string
        - name: is_statevector
          in: query
          description: is_statevector
          required: true
          schema:
            type: string
            default: False
        - name: iteration
          in: query
          description: iteration
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Parameter Optimization Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OptResponse"
        '404':
          description: Classifier not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /plots/grid-generation/{job_id}:
    post:
      summary: Execute Circuits
      operationId: resources.classifier.Classifier.generate_grid
      tags:
        - classifiers
      parameters:
        - name: job_id
          in: path
          description: Job identifier
          required: true
          schema:
            type: string
        - name: data_url
          in: query
          description: data_url
          required: true
          schema:
            type: string
        - name: resolution
          in: query
          description: resolution
          required: true
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: Grid Generation Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GridResponse"
        '404':
          description: Classifier not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /plots/prediction/{job_id}:
    post:
      summary: Predict
      operationId: resources.classifier.Classifier.predict
      tags:
        - classifiers
      parameters:
        - name: job_id
          in: path
          description: Job identifier
          required: true
          schema:
            type: string
        - name: results_url
          in: query
          description: results_url
          required: true
          schema:
            type: string
        - name: is_statevector
          in: query
          description: is_statevector
          required: true
          schema:
            type: string
            default: False
        - name: n_classes
          in: query
          description: iteration
          required: true
          schema:
            type: integer
            default: 2
      responses:
        '200':
          description: Predict Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PredictResponse"
        '404':
          description: Classifier not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /plots/plot/{job_id}:
    post:
      summary:  Plots data and decision boundary
      operationId: resources.classifier.Classifier.plot_boundary
      tags:
        - classifiers
      parameters:
        - name: job_id
          in: path
          description: Job identifier
          required: true
          schema:
            type: string
        - name: data_url
          in: query
          description: data_url
          required: true
          schema:
            type: string
        - name: labels_url
          in: query
          description: labels_url
          required: true
          schema:
            type: string
        - name: grid_url
          in: query
          description: grid_url
          required: true
          schema:
            type: string
        - name: predicitons_url
          in: query
          description: predicitons_url
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Plot Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlotResponse"
        '404':
          description: Classifier not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    InitResponse:
      required:
        - message
      properties:
        status_code:
          type: number
          format: integer
        message:
          type: string
        thetas_url:
          type: string
        thetas_plus_url:
          type: string
        thetas_minus_url:
          type: string
        delta_url:
          type: string
    OptResponse:
      required:
        - message
      properties:
        status_code:
          type: number
          format: integer
        message:
          type: string
        thetas_out_url:
          type: string
        thetas_plus_url:
          type: string
        thetas_minus_url:
          type: string
        delta_url:
          type: string
        costs_curr:
          type: integer
    GenResponse:
      required:
        - message
      properties:
        status_code:
          type: number
          format: integer
        message:
          type: string
        parameterizations_url:
          type: string
    PredictResponse:
      required:
        - message
      properties:
        status_code:
          type: number
          format: integer
        message:
          type: string
        predictions_url:
          type: string
    PlotResponse:
      required:
        - message
      properties:
        status_code:
          type: number
          format: integer
        message:
          type: string
        plot_url:
          type: string
    GridResponse:
      required:
        - message
      properties:
        status_code:
          type: number
          format: integer
        message:
          type: string
        grid_url:
          type: string
    ExeResponse:
      required:
        - message
      properties:
        status_code:
          type: number
          format: integer
        message:
          type: string
        results_url:
          type: string
        is_statevector:
          type: boolean
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
    DeleteMsg:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string